In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler(copy=True, feature_range=(0, 1))

In [3]:
data=pd.read_csv('C:\\Users\\SHINEROSE\\Downloads\\Lesson 10 -1\\auto_data.csv')

In [3]:
#we engage in data scaling because the features has different units of measurement which makes it difficult to compare the effect of one feature with another.

In [14]:
#data_x = data[['displacement','horsepower','acceleration','weight','mpg']]

In [17]:
#scaledX = scale.fit_transform(data_x.select_dtypes(np.number))

In [18]:
#print(scaledX)

[[0.61757106 0.23809524 0.5361497  0.2393617 ]
 [0.72868217 0.20833333 0.58973632 0.15957447]
 [0.64599483 0.17857143 0.51686986 0.2393617 ]
 ...
 [0.17312661 0.21428571 0.19336547 0.61170213]
 [0.13436693 0.63095238 0.2869294  0.50531915]
 [0.13178295 0.67857143 0.31386447 0.58510638]]


In [21]:
#scaling=scaledX.copy()
print(scaling)

[[0.61757106 0.23809524 0.5361497  0.2393617 ]
 [0.72868217 0.20833333 0.58973632 0.15957447]
 [0.64599483 0.17857143 0.51686986 0.2393617 ]
 ...
 [0.17312661 0.21428571 0.19336547 0.61170213]
 [0.13436693 0.63095238 0.2869294  0.50531915]
 [0.13178295 0.67857143 0.31386447 0.58510638]]


In [7]:
data_scale=data.copy()

In [10]:
data_scale['displacement'] = scale.fit_transform(data['displacement'].values.reshape(-1, 1))
#data_scale['horsepower'] = scale.fit_transform(data['horsepower'].astype(float).values.reshape(-1, 1))
data_scale['acceleration'] = scale.fit_transform(data['acceleration'].values.reshape(-1, 1))
data_scale['weight'] = scale.fit_transform(data['weight'].values.reshape(-1, 1))
data_scale['mpg'] =scale.fit_transform(data['mpg'].values.reshape(-1, 1))

In [11]:
data_scale.head()

mpg  cylinders  displacement horsepower    weight  acceleration  \
0  0.239362          8      0.617571        130  0.536150      0.238095   
1  0.159574          8      0.728682        165  0.589736      0.208333   
2  0.239362          8      0.645995        150  0.516870      0.178571   
3  0.186170          8      0.609819        150  0.516019      0.238095   
4  0.212766          8      0.604651        140  0.520556      0.148810   

   model_year  origin                       name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          70       1              amc rebel sst  
4          70       1                ford torino

In [16]:
data_scale['Country_code'] = data_scale['origin'].replace([1,2,3],['USA','Europe','Japan'])

In [17]:
data_scale.head()

mpg  cylinders  displacement horsepower    weight  acceleration  \
0  0.239362          8      0.617571        130  0.536150      0.238095   
1  0.159574          8      0.728682        165  0.589736      0.208333   
2  0.239362          8      0.645995        150  0.516870      0.178571   
3  0.186170          8      0.609819        150  0.516019      0.238095   
4  0.212766          8      0.604651        140  0.520556      0.148810   

   model_year  origin                       name Country_code  
0          70       1  chevrolet chevelle malibu          USA  
1          70       1          buick skylark 320          USA  
2          70       1         plymouth satellite          USA  
3          70       1              amc rebel sst          USA  
4          70       1                ford torino          USA

In [18]:

import seaborn as sb
style.use('ggplot')
data_scale_plot = pd.concat([data_scale['mpg'], data_scale['Country_code']], axis=1)
f, ax = plt.subplots(figsize=(8, 6))
fig = sb.boxplot(x=var, y="mpg", data=data_plt)
fig.axis(ymin=0, ymax=1)
plt.axhline(data_scale.mpg.mean(),color='r',linestyle='dashed',linewidth=2)

NameError: name 'style' is not defined